name: Valid JSON

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12_beta_2.app && xcodebuild -version
    - name: Validate JSON
      run: swift validate.swift
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
