name: Valid JSON

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: macos-11.1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Validate JSON
      run: xcrun swift validate.swift
      env:
        DEVELOPER_DIR: /Applications/Xcode_12.2.app
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validate-new:
    runs-on: macos-11.1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Validate JSON
      run: xcrun swift .validate-new.swift
      env:
        DEVELOPER_DIR: /Applications/Xcode_12.2.app
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
