name: Nightly Audit

on: 
  # workflow_dispatch:
  # schedule:
  #   - cron: '0 2 * * *'
  push:

jobs:
  run_nightly:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check redirects
      run: |
        curl -O "https://raw.githubusercontent.com/SwiftPackageIndex/Validator/main/validator"
        chmod +x validator
        ./validator check-redirects --use-package-list -o packages.json -l 10
        cat packages.json

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Updated Packages
        title: '[Nightly] Updated Packages'
        body: |
          :robot: This is an automated change
          
          - Removed any redirects
          - Removed any duplicates
          - Removed any deleted repositories
          - Added any unknown dependencies
    - name: Check outputs
      run: echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
